name: sup-indexer
description: Show Up Protocol indexer
contracts:
  - name: ShowHub
    handler: src/EventHandlers.ts
    events:
      - event: Canceled(uint256 indexed id, string reason, bytes data, address sender, uint256 timestamp)
        requiredEntities:
          - name: Record
      - event: CheckedIn(uint256 indexed id, address[] attendees, bytes data, address sender, uint256 timestamp)
        requiredEntities:
          - name: Record
          - name: User
          - name: Registration
      - event: ConditionModuleWhitelisted(address indexed conditionModule, string name, bool indexed whitelisted, address sender, uint256 timestamp)
        requiredEntities:
          - name: ConditionModule
      - event: Created(uint256 indexed id, string contentUri, uint256 endDate, uint256 limit,address indexed conditionModule, bytes data, address sender, uint256 timestamp)
        requiredEntities:
          - name: Record
          - name: ConditionModule
          - name: ConditionModuleData
      - event: Funded(uint256 indexed id, bytes data, address sender, uint256 timestamp)
        requiredEntities:
          - name: Record
          - name: ConditionModule
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
        requiredEntities:
          - name: Record
      - event: Registered(uint256 indexed id, address indexed participant, bytes data, address sender, uint256 timestamp)
        requiredEntities:
          - name: Record
          - name: User
          - name: Registration
      - event: Settled(uint256 indexed id, bytes data, address sender, uint256 timestamp)
        requiredEntities:
          - name: Record
      - event: Updated(uint256 indexed id, string contentUri, uint256 limit, address owner, address sender, uint256 timestamp)
        requiredEntities:
          - name: Record
networks:
  - id: 11155111 # Sepolia
    start_block: 0
    contracts:
      - name: ShowHub
        address: 0x896Ae5df06B9f8e14CB0d5d607Fc40b1E57E27a3
  - id: 84532 # Base Sepolia
    start_block: 0
    contracts:
      - name: ShowHub
        address: 0x2B52D9d2c1854dEaB06D16283Bfa710AAb9fE568
    hypersync_config:
      url: https://base-sepolia.hypersync.xyz
